server-id: 81748230 # um long but dont collide with discord guilds plz
music-token: "" # well api key
music-host: "" # um server ip thingy
music-port: 2677 # server port
resample-default-volume: 40 #0-100 better leave this as 40